note/models.py
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Note:
    _id: str
    title: str
    date: datetime.today()
    content: str

note/__init__.py
import os

from dotenv import load_dotenv
from flask import Flask
from pymongo import MongoClient

from note.routes import pages

load_dotenv()


def create_app():
    app = Flask(__name__)
    app.config["MONGODB_URI"] = os.environ.get("MONGODB_URI")
    app.config["SECRET_KEY"] = os.environ.get(
        "SECRET_KEY", "pf9Wkove4IKEAXvy-cQkeDPhv9Cb3Ag-wyJILbq_dFw"
    )
    app.db = MongoClient(app.config["MONGODB_URI"]).get_default_database()

    app.register_blueprint(pages)
    return app

note/routes.py
import datetime
import uuid
from dataclasses import asdict

from flask import (Blueprint, abort, current_app, redirect, render_template,
                   request, url_for)

from note.models import Note

pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


@pages.route("/")
def index():
    notes_data = current_app.db.note.find({})
    notes = [Note(**note) for note in notes_data]
    return render_template("index.html", title="Notes", notes=notes)

@pages.route("/add", methods=["GET", "POST"])
def add_note():
    if request.method == "POST":
        note = Note(
            _id = uuid.uuid1().hex,
            title = request.form.get("title"),
            date = datetime.datetime.today().strftime("%Y-%m-%d"),
            content = request.form.get("content")
        )
        current_app.db.note.insert_one(asdict(note))
        
        return redirect(url_for(".index"))
    
    return render_template("new_note.html", title="Notes | add note")

@pages.get("/note/<string:_id>")
def note(_id: str):
    note_data = current_app.db.note.find_one({'_id': _id})
    if not note_data:
        abort(404)
    note = Note(**note_data)
    return render_template("note_details.html", note=note)


@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
def edit_note(_id: str):
    note_data = current_app.db.note.find_one({'_id': _id})
    if not note_data:
        abort(404)
    note = Note(**note_data)
    
    if request.method == "POST":
        note.title = request.form.get("title")
        note.date = datetime.datetime.today().strftime("%Y-%m-%d")
        note.content = request.form.get("content")
        
        current_app.db.note.update_one({'_id': _id}, {'$set': asdict(note)})
        
        return redirect(url_for(".note", _id=_id))
    
    return render_template("edit_note.html", note=note)

@pages.get("/remove/<string:_id>")
def remove_note(_id: str):
    current_app.db.note.delete_one({'_id': _id})
    return redirect(url_for(".index"))

note/templates/edit_note.html
{% extends 'layout.html' %}
{% block main_content %}
<form method="POST" class="form">
    <div class="form__input">
        <input type="text", name="title" class="form__title" placeholder="Title" value="{{ note.title }}">
        <textarea name="content" class="form__content" placeholder="Type here">{{ note.content }}</textarea>
    </div>
    <button class="form__submit">Save</button>
</form>
{% endblock %}

note/templates/index.html
{% extends 'layout.html' %}
{% block main_content %}
{% if notes %}
    <div class="notes">
        {% for note in notes %}
            <div class="note">
                <div class="title_date">
                    <a href="{{ url_for('pages.note', _id=note._id) }}" class="note__link"></a>
                    <h1 class="note__title">{{ note.title }}</h1>
                    <h3 class="note__date">{{ note.date }}</h3>
                    <a href="{{ url_for('pages.remove_note', _id=note._id) }}" class="note__remove">remove</a>
                </div>
                <div class="note__content">{{ note.content }}</div>
            </div>
        {% endfor %}
    </div>
{% endif %}
<a href="{{ url_for('pages.add_note') }}" class="button">+ add note</a>
{% endblock %}

note/templates/layout.html
{% from 'macros/header.html' import header %}
<!-- {% from 'macros/footer.html' import footer %} -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{{ title | default('Note') }}</title>
    <link
      href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap"
      rel="stylesheet"
    />

    <link
      href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@300&family=Lato:wght@300&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/reset.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />

    {% block head_content %} {% endblock %}
  </head>

  <body>
    {{ header() }}
    <main class="main">{% block main_content %} {% endblock %}</main>
  </body>
</html>

note/templates/macros/footer.html
{% macro footer() %}
<footer class="footer">
    <small>Copyright &copy;2023. Note. All rights reserved.</small>
</footer>
{% endmacro %}

note/templates/macros/header.html
{% macro header() %}
<header class="header">
        <a href="{{ url_for('pages.index') }}" class="header__logo">
            <span class="logo__name">Note</span>
        </a>

        <div class="search__box">
            <input type="search" class="search__input" placeholder="Type to search">
            <button class="search__button">
                <img src="{{ url_for('static', filename='images/search.svg') }}" width="40">
            </button>    
        </div>

        <div class="nav__links">
            <a href="#" class="nav__link">register</a>
            <a href="#" class="nav__link">login</a>
        </div>
</header>
{% endmacro %}

note/templates/new_note.html
{% extends 'layout.html' %}
{% block main_content %}
<form method="POST" class="form">
    <div class="form__input">
        <input type="text", name="title" class="form__title" placeholder="Title">
        <textarea name="content" class="form__content" placeholder="Type here"></textarea>
    </div>
    <button class="form__submit">Save</button>
</form>
{% endblock %}

note/templates/note_details.html
{% extends 'layout.html' %}
{% block main_content %}
    <div class="note__head">
        <h1 class="title">{{ note.title }}</h1>
        <h5 class="date">{{ note.date }}</h5>
        <a href="{{ url_for('pages.edit_note', _id=note._id) }}" class="link">edit</a>
    </div>
    <h3 class="content">{{ note.content }}</h3>
{% endblock %}